# Copyright 2023 Hewlett-Packard Enterprise Development LP.
# All rights reserved.

---
# You must disable selinux or change it to Permissive mode on all the cluster nodes. 
# This is required to allow containers to access the host filesystem, 
# which is needed by pod networks
- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
  tags:
    - preinstall
    - selinux

- name: Disable FirewallD
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  tags:
    - preinstall
    - firewall